### ISSUE TITLE
UnicodeEncodeError windows 7

### ISSUE THREAD

**Issue by rolia17** [adampresley/sublime-view-in-browser#28]
Python version 2
OS name: posix, Platform: .*
OS name: nt, Platform: win32
Match! C:/Program Files/Mozilla Firefox/firefox.exe
Writing file /D/Work/АНКЕТА САЙТ/html-old/registration.html with encoding UTF-8
('Opening ', u'D:\Work\\u0410\u041d\u041a\u0415\u0422\u0410 \u0421\u0410\u0419\u0422\html-old\registration.html')
C:/Program Files/Mozilla Firefox/firefox.exe %s
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\ViewInBrowserCommand.py", line 111, in run
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-13: ordinal not in range(128)

What is this? Package don't work!

**Comment by mcclone2001** [comment]
Same error here, but different line number
`View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "ViewInBrowserCommand in C:\Users\Iván\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 201, in run
  File "ViewInBrowserCommand in C:\Users\Iván\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 176, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\Iván\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 85, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\Iván\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 67, in expandWindowsUserShellFolder
  File "ViewInBrowserCommand in C:\Users\Iván\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 137, in getWindowsUserShellFolders
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 11: ordinal not in range(128)`
