### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by henbenla** [adampresley/sublime-view-in-browser#37]
View In Browser plugin v2.0.0, Python 3
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab file:///E:/web/jQuery实战（第2版）源代码/chapter2/dom.sample.page.html
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 235, in run
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 188, in openBrowser
  File "./subprocess.py", line 824, in **init**
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by GrantSP** [comment]
So I've just returned to Sublime Text 3 build 3083 and apparently this is still an issue.
Any idea when this might be addressed?

Win64 Professional with a completely fresh install of Sublime.

**Comment by woodliu** [comment]
how to slove it ....

**Comment by huyongde** [comment]
how to solve it .........
