### ISSUE TITLE
"TypeError" when view in Chrome64

### ISSUE THREAD

**Issue by codepuncher** [adampresley/sublime-view-in-browser#38]
Just installed to test this out, works fine in Firefox.

However with Chrome64 (not sure if will have same issue with 32bit) I get this in my console, and no page is opened in browser:

```
View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "ViewInBrowserCommand in C:\Users\lee.hanbury.GINGERNUT\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 198, in run
  File "ViewInBrowserCommand in C:\Users\lee.hanbury.GINGERNUT\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 173, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\lee.hanbury.GINGERNUT\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 82, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\lee.hanbury.GINGERNUT\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 68, in expandWindowsUserShellFolder
TypeError: expected bytes, bytearray or buffer compatible object
```

Any ideas of what would cause this, or how to resolve?

**Comment by fchai88** [comment]
Hey I am also having the same issue and I am running Version 39.0.2171.95 m

I also changed my default browser in the "View in Browser" settings to chrome, along with the correct directory to the application. Thanks in advance.

**Comment by adampresley** [comment]
Can you attach a snapshot of the error and your configuration files for the plugin please?

**Comment by fchai88** [comment]
![trouble shoot_view browser](https://cloud.githubusercontent.com/assets/10409614/5622353/4214b9f0-9510-11e4-8202-6657a3bc7a6a.png)

Hope this helps, let me know if you need anything else.

**Comment by krypsin** [comment]
My Chrome appears to be installed to:
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
So, really I am starting to think it's just looking in the wrong place.
I am using the default settings in View In Browser; I haven't touched anything.

	{
		"posix": {
			"linux": {
				"firefox": "firefox -new-tab",
				"chrome": "google-chrome",
				"chrome64": "google-chrome",
				"chromium": "chromium"
			},
			"linux2": {
				"firefox": "firefox -new-tab",
				"chrome": "google-chrome",
				"chrome64": "google-chrome",
				"chromium": "chromium"
			},
			"darwin": {
				"firefox": "open -a \"/Applications/Firefox.app\"",
				"safari": "open -a \"/Applications/Safari.app\"",
				"chrome": "open -a \"/Applications/Google Chrome.app\"",
				"chrome64": "open -a \"/Applications/Google Chrome.app\""
			}
		},
		"nt": {
			"win32": {
				"firefox": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe -new-tab",
				"iexplore": "C:\\Program Files\\Internet Explorer\\iexplore.exe",
				"chrome": "%Local AppData%\\Google\\Chrome\\Application\\chrome.exe",
				"chrome64": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
			}
		},

		"browser": "firefox"
	}
![image](https://cloud.githubusercontent.com/assets/8135396/6165487/42667ac6-b2a0-11e4-89ec-3e45db98f26a.png)

**Comment by titosust** [comment]
I've faced same error!
But when i checked for  Chrome installation, i found its located in:
C:\Program Files\Google\Chrome\Application\chrome.exe

After overriding that path in user settings solved my problem.
Thanks.
