### ISSUE TITLE
unable to open chrome 

### ISSUE THREAD

**Issue by kalicomputers** [adampresley/sublime-view-in-browser#41]
my default browser is chrome 64bit but it cannot open I set default browser as you say but it dont work
following error may occure

Unable to open /C/Users/kali/AppData/Roaming/Sublime Text 3/Packages/View In Browser/View In Browser.sublime-settings
Writing file /C/Users/kali/AppData/Roaming/Sublime Text 3/Packages/User/View In Browser.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/View In Browser.sublime-settings
View In Browser plugin v2.0.0, Python 3
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab file:///C:/Users/kali/AppData/Roaming/Sublime%20Text%203/Packages/View%20In%20Browser/View%20In%20Browser.sublime-settings
View In Browser plugin v2.0.0, Python 3
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab file:///C:/Users/kali/AppData/Roaming/Sublime%20Text%203/Packages/View%20In%20Browser/View%20In%20Browser.sublime-settings
View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, *_args)
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 198, in run
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 173, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 82, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 68, in expandWindowsUserShellFolder
TypeError: expected bytes, bytearray or buffer compatible object
reloading Packages/User/View In Browser.sublime-settings
Unable to open /C/Users/kali/AppData/Roaming/Sublime Text 3/Packages/User/View In Browser.sublime-settings
Writing file /C/Users/kali/AppData/Roaming/Sublime Text 3/Packages/User/View In Browser.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/View In Browser.sublime-settings
View In Browser plugin v2.0.0, Python 3
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab file:///C:/Users/kali/AppData/Roaming/Sublime%20Text%203/Packages/User/View%20In%20Browser.sublime-settings
View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, *_args)
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 198, in run
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 173, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 82, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 68, in expandWindowsUserShellFolder
TypeError: expected bytes, bytearray or buffer compatible object
View In Browser plugin v2.0.0, Python 3
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab file:///C:/xampp/htdocs/wrox/1.php
View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 198, in run
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 173, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 82, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\kali\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 68, in expandWindowsUserShellFolder
TypeError: expected bytes, bytearray or buffer compatible object

**Comment by tjr8** [comment]
I'm running into the same problem. Won't work with chrome.

**Comment by jsenne** [comment]
I'm having the same problem.

**Comment by jameslh** [comment]
I had the same issue when using the windows variable paths (%AppData% etc). It worked when I configured chrome as "chrome": "C:\\\\Users\\\\&lt;MyUserName&gt;\\\\AppData\\Local\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe"

**Comment by kaona** [comment]
Same problem here. Actually, none of the browsers open. My View In Browser.sublime.settings is the default file. It has not been changed. Has this issue been addressed?

I then created "view in browser.sublime-settings" - Default with:
{
   "selectedBrowser": "chrome"
}
This is "View In Browser.sublime-settings - Default
{
	"posix": {
		"linux": {
			"firefox": "firefox -new-tab",
			"chrome": "google-chrome",
			"chrome64": "google-chrome",
			"chromium": "chromium"
		},
		"linux2": {
			"firefox": "firefox -new-tab",
			"chrome": "google-chrome",
			"chrome64": "google-chrome",
			"chromium": "chromium"
		},
		"darwin": {
			"firefox": "open -a \"/Applications/Firefox.app\"",
			"safari": "open -a \"/Applications/Safari.app\"",
			"chrome": "open -a \"/Applications/Google Chrome.app\"",
			"chrome64": "open -a \"/Applications/Google Chrome.app\"",
			"yandex": "open -a \"/Applications/Yandex.app\""
		}
	},
	"nt": {
		"win32": {
			"firefox": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe -new-tab",
			"iexplore": "C:\\Program Files\\Internet Explorer\\iexplore.exe",
			"chrome": "%Local AppData%\\Google\\Chrome\\Application\\chrome.exe",
			"chrome64": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
			"yandex": "%Local AppData%\\Yandex\\YandexBrowser\\browser.exe"
		}
	},

	"browser": "firefox"
}

Thank you.

**Comment by sami3d** [comment]
Same problem here ... not working on chrome. I dont have firefox installed so nothing happens when I click on the view in browser tab. Anyway, going to remove this package. Seems total waste of time.

**Comment by binoyc** [comment]
replace "chrome": "%Local AppData%\Google\Chrome\Application\chrome.exe", with 
"chrome": "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",

override in user settings (Preferences -> Package Settings -> View in Browser -> Settings-user )
