### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by henbenla** [adampresley/sublime-view-in-browser#42]
View In Browser plugin v2.0.0, Python 3
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 198, in run
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 173, in loadPluginSettings
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 82, in getBaseCommand
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 64, in expandWindowsUserShellFolder
  File "ViewInBrowserCommand in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\View In Browser.sublime-package", line 134, in getWindowsUserShellFolders
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-6: ordinal not in range(128)

**Comment by pwcong** [comment]
I hava met the same problem.
How can i resolve it?
